//This is an autogenerated file.
 #pragma once


#include <stdio.h>
#include <stdint.h>

#define BROADCAST 0xFE

typedef enum
{
    model_number,
    model_information,
    firmware_version,
    id,
    baud_rate,
    return_delay_time,
    drive_mode,
    operating_mode,
    secondary_shadow_id,
    protocol_type,
    homing_offset,
    moving_threshold,
    temperature_limit,
    max_voltage_limit,
    min_voltage_limit,
    pwm_limit,
    current_limit,
    velocity_limit,
    max_position_limit,
    min_position_limit,
    startup_configuration,
    pwm_slope,
    shutdown,
    LAST_EEPROM
}eeprom_regs_enum_t;

typedef struct
{
    uint16_t model_number;
    uint32_t model_information;
    uint8_t firmware_version;
    uint8_t id;
    uint8_t baud_rate;
    uint8_t return_delay_time;
    uint8_t drive_mode;
    uint8_t operating_mode;
    uint8_t secondary_shadow_id;
    uint8_t protocol_type;
    uint32_t homing_offset;
    uint32_t moving_threshold;
    uint8_t temperature_limit;
    uint16_t max_voltage_limit;
    uint16_t min_voltage_limit;
    uint16_t pwm_limit;
    uint16_t current_limit;
    uint32_t velocity_limit;
    uint32_t max_position_limit;
    uint32_t min_position_limit;
    uint8_t startup_configuration;
    uint8_t pwm_slope;
    uint8_t shutdown;
} eeprom_struct_t;

typedef enum
{
    torque_enable,
    led,
    status_return_level,
    registered_instruction,
    hardware_error_status,
    velocity_i_gain,
    velocity_p_gain,
    position_d_gain,
    position_i_gain,
    position_p_gain,
    feedforward_2nd_gain,
    feedforward_1st_gain,
    bus_watchdog,
    goal_pwm,
    goal_current,
    goal_velocity,
    profile_acceleration,
    profile_velocity,
    goal_position,
    realtime_tick,
    moving,
    moving_status,
    present_pwm,
    present_current,
    present_velocity,
    present_position,
    velocity_trajectory,
    position_trajectory,
    present_input_voltage,
    present_temperature,
    backup_ready,
    indirect_address_1,
    indirect_address_2,
    indirect_address_3,
    indirect_address_18,
    indirect_address_19,
    indirect_address_20,
    indirect_data_1,
    indirect_data_2,
    indirect_data_3,
    indirect_data_18,
    indirect_data_19,
    indirect_data_20,
    LAST_RAM
}ram_regs_enum_t;

typedef struct
{
    uint8_t torque_enable;
    uint8_t led;
    uint8_t status_return_level;
    uint8_t registered_instruction;
    uint8_t hardware_error_status;
    uint16_t velocity_i_gain;
    uint16_t velocity_p_gain;
    uint16_t position_d_gain;
    uint16_t position_i_gain;
    uint16_t position_p_gain;
    uint16_t feedforward_2nd_gain;
    uint16_t feedforward_1st_gain;
    uint8_t bus_watchdog;
    uint16_t goal_pwm;
    uint16_t goal_current;
    uint32_t goal_velocity;
    uint32_t profile_acceleration;
    uint32_t profile_velocity;
    uint32_t goal_position;
    uint16_t realtime_tick;
    uint8_t moving;
    uint8_t moving_status;
    uint16_t present_pwm;
    uint16_t present_current;
    uint32_t present_velocity;
    uint32_t present_position;
    uint32_t velocity_trajectory;
    uint32_t position_trajectory;
    uint16_t present_input_voltage;
    uint8_t present_temperature;
    uint8_t backup_ready;
    uint16_t indirect_address_1;
    uint16_t indirect_address_2;
    uint16_t indirect_address_3;
    uint16_t indirect_address_18;
    uint16_t indirect_address_19;
    uint16_t indirect_address_20;
    uint8_t indirect_data_1;
    uint8_t indirect_data_2;
    uint8_t indirect_data_3;
    uint8_t indirect_data_18;
    uint8_t indirect_data_19;
    uint8_t indirect_data_20;
} ram_struct_t;
