// Generated by gencpp from file robot_msgs/Light.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_LIGHT_H
#define ROBOT_MSGS_MESSAGE_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct Light_
{
  typedef Light_<ContainerAllocator> Type;

  Light_()
    : rgbw()
    , gesture(0)  {
    }
  Light_(const ContainerAllocator& _alloc)
    : rgbw(_alloc)
    , gesture(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _rgbw_type;
  _rgbw_type rgbw;

   typedef int32_t _gesture_type;
  _gesture_type gesture;





  typedef boost::shared_ptr< ::robot_msgs::Light_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::Light_<ContainerAllocator> const> ConstPtr;

}; // struct Light_

typedef ::robot_msgs::Light_<std::allocator<void> > Light;

typedef boost::shared_ptr< ::robot_msgs::Light > LightPtr;
typedef boost::shared_ptr< ::robot_msgs::Light const> LightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::Light_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::Light_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::Light_<ContainerAllocator1> & lhs, const ::robot_msgs::Light_<ContainerAllocator2> & rhs)
{
  return lhs.rgbw == rhs.rgbw &&
    lhs.gesture == rhs.gesture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::Light_<ContainerAllocator1> & lhs, const ::robot_msgs::Light_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Light_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Light_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::Light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba54a502272d86cc6063f7ba6b342cf5";
  }

  static const char* value(const ::robot_msgs::Light_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba54a502272d86ccULL;
  static const uint64_t static_value2 = 0x6063f7ba6b342cf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::Light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/Light";
  }

  static const char* value(const ::robot_msgs::Light_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::Light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] rgbw\n"
"int32 gesture\n"
;
  }

  static const char* value(const ::robot_msgs::Light_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::Light_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rgbw);
      stream.next(m.gesture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Light_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::Light_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::Light_<ContainerAllocator>& v)
  {
    s << indent << "rgbw[]" << std::endl;
    for (size_t i = 0; i < v.rgbw.size(); ++i)
    {
      s << indent << "  rgbw[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.rgbw[i]);
    }
    s << indent << "gesture: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gesture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_LIGHT_H
