// Generated by gencpp from file robot_msgs/NameList.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_NAMELIST_H
#define ROBOT_MSGS_MESSAGE_NAMELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_msgs/Name.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct NameList_
{
  typedef NameList_<ContainerAllocator> Type;

  NameList_()
    : names()  {
    }
  NameList_(const ContainerAllocator& _alloc)
    : names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_msgs::Name_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_msgs::Name_<ContainerAllocator> >::other >  _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::robot_msgs::NameList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::NameList_<ContainerAllocator> const> ConstPtr;

}; // struct NameList_

typedef ::robot_msgs::NameList_<std::allocator<void> > NameList;

typedef boost::shared_ptr< ::robot_msgs::NameList > NameListPtr;
typedef boost::shared_ptr< ::robot_msgs::NameList const> NameListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::NameList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::NameList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::NameList_<ContainerAllocator1> & lhs, const ::robot_msgs::NameList_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::NameList_<ContainerAllocator1> & lhs, const ::robot_msgs::NameList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::NameList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::NameList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::NameList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::NameList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::NameList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::NameList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::NameList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a56b0cece0aeebd6949775af9bc48613";
  }

  static const char* value(const ::robot_msgs::NameList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa56b0cece0aeebd6ULL;
  static const uint64_t static_value2 = 0x949775af9bc48613ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::NameList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/NameList";
  }

  static const char* value(const ::robot_msgs::NameList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::NameList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Name[] names\n"
"================================================================================\n"
"MSG: robot_msgs/Name\n"
"std_msgs/String name\n"
"std_msgs/UInt64 time\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt64\n"
"uint64 data\n"
;
  }

  static const char* value(const ::robot_msgs::NameList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::NameList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NameList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::NameList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::NameList_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_msgs::Name_<ContainerAllocator> >::stream(s, indent + "    ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_NAMELIST_H
