; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_nrf52840_sense]
platform = nordicnrf52
board = adafruit_feather_nrf52840_sense
framework = arduino
lib_archive = no
build_flags = 
	; -DDEBUG
	; -DDEBUGODOM
	-Isrc/motor_driver/dynamixel_headers
	-Isrc/singlewireserial
	-Isrc/crc
	-Isrc/router
	-Isrc/stream_headers
	-Isrc/tlm
	-Isrc/uart
	-Isrc/softwareserial

debug_tool = jlink

; SWD interface
upload_protocol = jlink

; ; JTAG interface
; upload_protocol = jlink-jtag
